### ISSUE TITLE
Failed query

### ISSUE THREAD

**Issue by bbockelm** [dmwm/das2go#1]
The following query fails in das2go but succeeds in das:

```
dataset site=T2_US_Nebraska
```

error message is "runtime error: index out of range"

**Comment by vkuznet** [comment]
Thanks for report. That's why I need time for integration tests, the code works
in my dev tree and local environment, but somehow I missed something on
production server (possibly overlap with DAS itself since I used shared DB and
maps, which needs to be adjusted).

**Comment by bbockelm** [comment]
No problem - I figured you'd find the bug report useful!

**Comment by vkuznet** [comment]
deployed to production
