### ISSUE TITLE
Add support for Rucio APIs

### ISSUE THREAD

**Issue by vkuznet** [dmwm/das2go#10]
The CMS Data Aggregation System (DAS) relies on the following PhEDEx APIs:

- https://cmsweb.cern.ch/phedex/datasvc/json/prod/TFC
- https://cmsweb.cern.ch/phedex/datasvc/json/prod/blockReplicas
- https://cmsweb.cern.ch/phedex/datasvc/json/prod/blockreplicasummary
- https://cmsweb.cern.ch/phedex/datasvc/json/prod/fileReplicas
- https://cmsweb.cern.ch/phedex/datasvc/json/prod/groups
- https://cmsweb.cern.ch/phedex/datasvc/json/prod/groupusage
- https://cmsweb.cern.ch/phedex/datasvc/json/prod/nodes
- https://cmsweb.cern.ch/phedex/datasvc/json/prod/nodeusage

But the main ones are blockReplicas and fileReplicas. Here are concrete examples of URL DAS places:
```
# fileReplicas example
https://cmsweb.cern.ch/phedex/datasvc/json/prod/fileReplicas?dataset=%2FZeroBias%2FRun2017F-31Mar2018-v1%2FNANOAOD
# blockReplicas example
https://cmsweb.cern.ch/phedex/datasvc/json/prod/blockReplicas?dataset=%2FZeroBias%2FRun2017F-31Mar2018-v1%2FNANOAOD
```
You can either use this URLs directly in a browser or use curl client, e.g.
```
curl -L -k --key ~/.globus/userkey.pem --cert ~/.globus/usercert.pem
"https://cmsweb.cern.ch/phedex/datasvc/json/prod/blockReplicas?dataset=%2FZeroBias%2FRun2017F-31Mar2018-v1%2FN
ANOAOD"
```
and then you can see returned JSON document.

To perform DAS+Rucio aggregation we need to get list of Rucio APIs for all PhEDEx APIs DAS uses.

**Comment by bbockelm** [comment]
Could you provide some insight on what the:
- Groups / group usage
- TFC
information is used for?  Those might be hard to replicate precisely.

As far as DAS is concerned, what's the difference between block replica and block replica summary.  What are the use cases?

**Comment by vkuznet** [comment]
Brian,
the group/TFC PhEDEx queries is part of "site" DAS query, but I doubt that we
need them anymore.

The blockReplicas and blockReplicasSummary are the same calls but latter returns
subset of information. It only returns replica names and sites, while former
returns full details of the replica, e.g. size, #files, node, se, complete
status, etc. Here is concrete example where I stripped off phedex wrapper:

```
# blockReplicas call
scurl "https://cmsweb.cern.ch/phedex/datasvc/json/prod/blockReplicas?dataset=%2FZeroBias%2FRun2017F-31Mar2018-v1%2FNANOAOD"
# phedex wrapper
{"phedex":{"request_version":"2.4.0pre1","request_timestamp":1536753549.746,"instance":"prod","request_call":"blockreplicas","request_url":"http://cmsweb.cern.ch:7001/phedex/datasvc/json/prod/blockReplicas","request_date":"2018-09-12 11:59:09 UTC",
# block info
"block":[{"bytes":4048505888,"files":11,"is_open":"n","name":"/ZeroBias/Run2017F-31Mar2018-v1/NANOAOD#0099f369-cedf-43b5-91ae-85f0e1dfbfbc","id":10030339,
"replica":[{"bytes":4048505888,"files":11,"node":"T0_CH_CERN_Export","time_create":1533263851,"time_update":1536601387.011,"group":null,"node_id":1,"custodial":"n","se":null,"subscribed":"n","complete":"y"},
           {"bytes":4048505888,"files":11,"node":"T2_US_MIT","time_create":1533835696,"time_update":1536601387.011,"group":"AnalysisOps","node_id":50,"custodial":"n","se":"se01.cmsaf.mit.edu","subscribed":"y","complete":"y"},
           {"bytes":4048505888,"files":11,"node":"T0_CH_CERN_MSS","time_create":1533263070,"time_update":1536601387.011,"group":"DataOps","node_id":2,"custodial":"y","se":"srm-cms.cern.ch","subscribed":"y","complete":"y"}]},
           {"bytes":22662510396,"files":52,"is_open":"n","name":"/ZeroBias/Run2017F-31Mar2018-v1/NANOAOD#ce2e8552-d33c-4018-b393-0ddfedbeab57","id":10029702,"replica":[{"bytes":22662510396,"files":52,"node":"T2_US_MIT","time_create":1533835696,"time_update":1536601122.93298,"group":"AnalysisOps","node_id":50,"custodial":"n","se":"se01.cmsaf.mit.edu","subscribed":"y","complete":"y"},{"bytes":22662510396,"files":52,"node":"T0_CH_CERN_Export","time_create":1533263851,"time_update":1536601122.93298,"group":null,"node_id":1,"custodial":"n","se":null,"subscribed":"n","complete":"y"},{"bytes":22662510396,"files":52,"node":"T0_CH_CERN_MSS","time_create":1533263070,"time_update":1536601122.93298,"group":"DataOps","node_id":2,"custodial":"y","se":"srm-cms.cern.ch","subscribed":"y","complete":"y"}]}],"call_time":"0.00848"}}

# blockReplicasummary call
scurl "https://cmsweb.cern.ch/phedex/datasvc/json/prod/blockReplicasummary?dataset=%2FZeroBias%2FRun2017F-31Mar2018-v1%2FNANOAOD"
# phedex wrapper
{"phedex":{"request_version":"2.4.0pre1","request_timestamp":1536753586.83267,"instance":"prod","request_call":"blockreplicasummary","request_url":"http://cmsweb.cern.ch:7001/phedex/datasvc/json/prod/blockReplicasummary","request_date":"2018-09-12 11:59:46 UTC",
# block info
"block":[{"name":"/ZeroBias/Run2017F-31Mar2018-v1/NANOAOD#0099f369-cedf-43b5-91ae-85f0e1dfbfbc",
"replica":[{"node":"T0_CH_CERN_Export","complete":"y"},
           {"node":"T2_US_MIT","complete":"y"},
           {"node":"T0_CH_CERN_MSS","complete":"y"}]},
         {"name":"/ZeroBias/Run2017F-31Mar2018-v1/NANOAOD#ce2e8552-d33c-4018-b393-0ddfedbeab57","replica":[{"node":"T2_US_MIT","complete":"y"},{"node":"T0_CH_CERN_Export","complete":"y"},{"node":"T0_CH_CERN_MSS","complete":"y"}]}],"call_time":"0.00770"}}
```

The blockreplicasummary there is more efficient in terms of response size and time
and used where no detailed information is required.

Best,
Valentin.

**Comment by bbockelm** [comment]
Thanks.

Can you look up the statistics on the usage of the `site` query?  If it's relatively unused, we should just look into removing it.

**Comment by kdziedzi** [comment]
I've got the stats from Lina:
Most of DAS queries to phedex are against: 
- blockReplicas 
- fileReplicas

Is possible, that there are a rera request for APIs below but in general,  they are not requested, according to the logs (One exception is below [1]: 
TFC
groups
groupsusage
nodes
nodeusage

[1]
[28/May/2018:17:16:11 +0200] "GET /phedex/datasvc/json/prod/nodeusage?dataset=/GenericTTbar/SAM-CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/AODSIM&node=T2_PL_Warsaw HTTP/1.1" 400 222 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0"
