### ISSUE TITLE
Add support to Dynamo

### ISSUE THREAD

**Issue by cpausmit** [dmwm/das2go#14]
The Dynamo team (mostly Max) has completed the APIs which very closely match the phedex APIs. What one would have to do is to substitute
  https://cmsweb.cern.ch/phedex/datasvc/json/prod/
with
  http://dynamo.mit.edu/phedexdata/inventory/subscriptions
the rest of the call and options are the same. All dynamo APIs take exactly the same options. The returned jsons structurally are the same as the PhEDEx ones (if not then it is a mistake and will be corrected). The difference in reply would be object ids (dataset id, site id), as dynamo returns numbers that are internal to dynamo. We also omit some fields that dynamo does not have (instead of faking them), please let us know if any of them are actually used by the code so that we could adjust dynamo code. Some smaller issues in one of the API calls is still in progress but thi should be close enough for many tests.

Please let me know if you have any questions or need this to be posted somewhere else.

**Comment by bbockelm** [comment]
As we said today in the CMS O&C week Data Management Transition plan, we aren't planning to utilize the Dynamo APIs within DMWM and will be focusing our effort on the Rucio APIs.
