### ISSUE TITLE
web UI misreports site lists

### ISSUE THREAD

**Issue by belforte** [dmwm/das2go#15]
While investigating some crab submission problem report we found the following:
This datase is on tape at CCIN2P3 with just one block on disk in Pisa, dasgoclient correctly reports:
belforte@lxplus021/STE> dasgoclient  --query 'site dataset=/BsToMuMuPhi_BMuonFilter_SoftQCDnonD_TuneCUEP8M1_13TeV-pythia8-evtgen/RunIISummer16DR80Premix-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/AODSIM'
T1_FR_CCIN2P3_Buffer
T1_FR_CCIN2P3_MSS
T2_IT_Pisa
belforte@lxplus021/STE> 

While looking in DAS web UI the dataset is listed as being on tape only:
https://cmsweb.cern.ch/das/request?instance=prod/global&input=site+dataset%3D%2FBsToMuMuPhi_BMuonFilter_SoftQCDnonD_TuneCUEP8M1_13TeV-pythia8-evtgen%2FRunIISummer16DR80Premix-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1%2FAODSIM

When querying only for the block on disk, WEB UI reports correctly
 Block size: 217441549 (217.4MB) Number of files: 1 Open: n Site: T2_IT_Pisa, T1_FR_CCIN2P3_Buffer, T1_FR_CCIN2P3_MSS  at
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2FBsToMuMuPhi_BMuonFilter_SoftQCDnonD_TuneCUEP8M1_13TeV-pythia8-evtgen%2FRunIISummer16DR80Premix-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1%2FAODSIM%23e863f226-cb55-11e6-a2b6-001e67abf518

Maybe because 1 disk block out of 148 is somehow rounded to 0% and hence no listed by the
site dataset=... query in the UI ?

**Comment by vkuznet** [comment]
Stefano, you found a bug. Turns out I introduced when handle Original records from DBS. The T2_IT_Pisa is present in DBS as original placement record and it is (now) filtered out on web UI. I fixed issue in the master and will schedule it in next cmsweb upgrade.
