### ISSUE TITLE
Dataset view sub-info in random order

### ISSUE THREAD

**Issue by dntaylor** [dmwm/das2go#17]
When looking at the result of a dataset query, the information about the dataset below the dataset link is sometimes in a different order.

For example:

The query

https://cmsweb.cern.ch/das/request?input=dataset%3D%2FSUSYVBFToHToAA_AToMuMu_AToTauTau_M-300_M-5_TuneCUETP8M1_13TeV_madgraph_pythia8%2Fdntaylor-crab_2018-11-20_Skim_MuMuTauTau_VBF_80X_v1-d605b0133e938d0f7712cc7189836ff8%2FUSER&instance=prod/phys03

Results in a view like:

![image](https://user-images.githubusercontent.com/4513541/48801821-a695e800-ed0d-11e8-97b7-11662a7e5663.png)

whereas this query

https://cmsweb.cern.ch/das/request?input=dataset%3D%2FSUSYVBFToHToAA_AToMuMu_AToTauTau_M-300_M-9_TuneCUETP8M1_13TeV_madgraph_pythia8%2Fdntaylor-crab_2018-11-20_Skim_MuMuTauTau_VBF_80X_v1-d605b0133e938d0f7712cc7189836ff8%2FUSER&instance=prod/phys03

results in:

![image](https://user-images.githubusercontent.com/4513541/48801832-aeee2300-ed0d-11e8-83d9-6900794ece4b.png)

These change with a refresh (hence the attached screen shots).

Other formatting errors appear on refresh:

![image](https://user-images.githubusercontent.com/4513541/48801914-e230b200-ed0d-11e8-9852-7d5d3f54969b.png)

In this version, you see spaces before and after the slashes in the dataset link.

**Comment by vkuznet** [comment]
I fixed DAS master tree, will schedule it in next cmsweb upgrade.

**Comment by vkuznet** [comment]
in production
