### ISSUE TITLE
Web interface error

### ISSUE THREAD

**Issue by DryRun** [dmwm/das2go#18]
Hi, I hope this is the right place to report this. The web interface is not working for me right now:

Search string: `dataset=/ZMM*/*/*`, taken from the help page
Result:
```
DAS error
DAS query:
dataset=/ZMM*/*/*
^
Error: DAS QL ERROR, query=dataset = /ZMM*/*/*, idx=0, msg=Wrong DAS key: dataset 
```

Thanks,
David

**Comment by vkuznet** [comment]
David,
I just tried and it works for me. Could you please try it again and this time
try to **manually** type the query. Sometimes people cut and paste it from
somewhere and may be there is a hidden character. But it is also possible
that DAS experienced an issue by the time you place your query, the DAS QL
parser may fail too.

Also, you may try dasgoclient from any CMSSW release, just login to lxplus and do

voms-proxy-init -voms cms -rfc
dasgoclient -query="dataset=/ZMM*/*/*"

which should work too.

Best,
Valentin.

**Comment by DryRun** [comment]
Hi Valentin, thanks for the practically immediate reply! Unfortunately, I get similar errors typing out the query, and also using autocomplete to try queries that worked for me in the past. I also see the problem in Firefox and Chrome.

However, my officemate was able to use the web interface normally, so it does seem to be specific to my laptop. The command line client works for me, so I'll just use that now. Thanks!

**Comment by vkuznet** [comment]
My suggestion would be to clear up your browser cache. But CLI works much faster
then web UI and those who discover CLI interface usually never get back to web :)
