### ISSUE TITLE
missing file in dataset

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/das2go#19]
When I query for all of the files in the dataset

/SingleMuon/Run2016H-03Feb2017_ver2-v1/MINIAOD

I get a list

https://cmsweb.cern.ch/das/request?view=plain&limit=50&instance=prod%2Fglobal&input=file+dataset%3D%2FSingleMuon%2FRun2016H-03Feb2017_ver2-v1%2FMINIAOD

which does not include one of the valid files

https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=file+file%3D%2Fstore%2Fdata%2FRun2016H%2FSingleMuon%2FMINIAOD%2F03Feb2017_ver2-v1%2F80000%2F980FF331-B5EA-E611-A6A8-002590E2D9FE.root

**Comment by yuyiguo** [comment]
Hi Andrew,

I checked the file from DBS side and found that file is invalid. You might run:
```
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/files?dataset=/SingleMuon/Run2016H-03Feb2017_ver2-v1/MINIAOD&validFileOnly=1 ```

and you would not see the file. However, if you remove the validFileOnly=1, the file would show in the list.
Maybe the file was valid and invalid later on by someone.

Thanks,
Yuyi

**Comment by vkuznet** [comment]
no longer valid, closing the ticket.
