### ISSUE TITLE
list result format is always used

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/das2go#2]
Hi,

I selected the "plain" result format, but it always returns the "list" result format.

Compare:

https://cmsweb.cern.ch/das2go/request?view=plain&limit=50&instance=prod%2Fglobal&input=file+dataset%3D%2FWGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8%2FRunIISummer16NanoAOD-PUMoriond17_05Feb2018_94X_mcRun2_asymptotic_v2_ext3-v1%2FNANOAODSIM

and

https://cmsweb.cern.ch/das/request?view=plain&limit=50&instance=prod%2Fglobal&input=file+dataset%3D%2FWGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8%2FRunIISummer16NanoAOD-PUMoriond17_05Feb2018_94X_mcRun2_asymptotic_v2_ext3-v1%2FNANOAODSIM

Andrew

**Comment by vkuznet** [comment]
fixed on cmsweb-testbed, will schedule in June upgrade

**Comment by vkuznet** [comment]
deployed to production
