### ISSUE TITLE
Adding back the link of a dataset to McM

### ISSUE THREAD

**Issue by pgunnell** [dmwm/das2go#20]
Dear all,
would it be possible to add back the link of a MC dataset to the McM request?

We got a lot of queries about that and we think it might be useful.

Thanks in advance.

The Pdmv group

**Comment by vkuznet** [comment]
Could you please clarify explicitly on which DAS page and where it should be
added. My understanding that you want to add a new link called McM when
user query some dataset(s), e.g. this page:
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FZMM*%2F*%2F*
should have McM link next to XSDB, right?

If so, what link should represent? I mean please provide link content/URL.

**Comment by vkuznet** [comment]
There is no response on this ticket for 1/2 year, please provide requested information.

**Comment by pgunnell** [comment]
Sorry, I missed your reply: the button should send to the following page:

https://cms-pdmv.cern.ch/mcm/requests?produce=NAME_SAMPLE_IN_DAS&page=0&shown=127

if possible

**Comment by vkuznet** [comment]
What the NAME_SAMPLE_IN_DAS means? Is it a dataset name?Just take one concrete example in DAS and for that (dataset/block/file whatever you query in DAS or DAS page) show associative link (or series of steps) in McM to get link you want.

**Comment by pgunnell** [comment]
example for this sample:

/WprimeToWZToWhadZhad_M5500_TuneCP5_13TeV/RunIIFall18DRPremix-102X_upgrade2018_realistic_v11-v1/AODSIM

this is the link: 
https://cms-pdmv.cern.ch/mcm/requests?produce=/WprimeToWZToWhadZhad_M5500_TuneCP5_13TeV/RunIIFall18DRPremix-102X_upgrade2018_realistic_v11-v1/AODSIM&page=0&shown=127

**Comment by vkuznet** [comment]
The fix now in master, will schedule it in next cmsweb upgrade cycle.

**Comment by pgunnell** [comment]
Thanks a lot
