### ISSUE TITLE
dataset lookup from file not working anymore?

### ISSUE THREAD

**Issue by hufnagel** [dmwm/das2go#21]
This doesn't get any results

dataset file=/store/mc/RunIISummer19ULPrePremix/Neutrino_E-10_gun/PREMIX/UL17_106X_mc2017_realistic_v6-v1/30001/3DBDCDA1-E656-814A-BE78-C0ACDB9C05E0.root

while doing a block lookup first and then getting the dataset from the block works fine.

**Comment by vkuznet** [comment]
Dirk, does it still fails for you? I just did the following:
```
ssh lxplus
voms-proxy-init -voms cms
dasgoclient -query="dataset file=/store/mc/RunIISummer19ULPrePremix/Neutrino_E-10_gun/PREMIX/UL17_106X_mc2017_realistic_v6-v1/30001/3DBDCDA1-E656-814A-BE78-C0ACDB9C05E0.root"
/Neutrino_E-10_gun/RunIISummer19ULPrePremix-UL17_106X_mc2017_realistic_v6-v1/PREMIX
```
and the same query works on web interface too.
So it works for just fine.

I suspect it was the issue either with DAS server or ongoing reboot of VMs.

I'm closing this issue for now, but if it does not work for you please re-open and provide details.
