### ISSUE TITLE
Adding button for directly get the cmsDriver from a dataset in DAS

### ISSUE THREAD

**Issue by pgunnell** [dmwm/das2go#24]
Would it be possible to add one button in DAS to get the cmsDriver directly from a dataset page? This has been discussed many times and would be very beneficial especially for RelVal samples.

**Comment by vkuznet** [comment]
Please remind me details and/or provide them here. To make a button we need to form a link, if we're on dataset page we know dataset name, so what would be the link to cmsDriver knowing the dataset name?

**Comment by pgunnell** [comment]
For this sample:

https://cmsweb.cern.ch/das/request?view=list&input=%2FJetHT%2FRun2017B-pilot-v1%2FNANOAOD

the link should point to:

https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/df0681ff88a4337a2c37ddb4561ba84c/configFile

which is the link to the reqmgr page.

**Comment by vkuznet** [comment]
And, it will save me time if you'll provide all steps how to get this link from a dataset name. It should be series of URL calls to ReqMgr2 to get this config. What they are?

**Comment by vkuznet** [comment]
I looked at this request closely and I think DAS already provides this functionality via config query, eg.

config dataset=/4B_TuneZ2_7TeV-alpgen-pythia6/Summer11-START311_V2-v3/GEN-SIM
provides a page to possible config files.

Here is a direct link
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=config+dataset%3D%2F4B_TuneZ2_7TeV-alpgen-pythia6%2FSummer11-START311_V2-v3%2FGEN-SIM

**Comment by vkuznet** [comment]
And, using your dataset

config dataset=/JetHT/Run2017B-pilot-v1/NANOAOD


https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=config+dataset%3D%2FJetHT%2FRun2017B-pilot-v1%2FNANOAOD

**Comment by pgunnell** [comment]
For this sample:

https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FSingleElectron%2FRun2017F-31Mar2018-v1%2FMINIAOD

I click on Configs:

https://cmsweb.cern.ch/das/request?instance=prod/global&input=config+dataset%3D%2FSingleElectron%2FRun2017F-31Mar2018-v1%2FMINIAOD

Then on ReqMgr2 -> output-config0

which brings to:
https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/9c970f83004787908c257e6157ddf52e/configFile

**Comment by vkuznet** [comment]
So, why it is not satisfactory?

**Comment by vkuznet** [comment]
The config query is a multi step and having linked to dataset page which may show mutliple entires if user supplies a dataset pattern can complicate things significantly.

Moreover, the config is not only ReqMgr2 query since configs can come from DBS, so I doubt that having direct link (which needs to be resolved for every single dataset) is worth of effort. For instance, the underlying system (ReqMgr2) may go down or timeout, which implies that DAS dataset query will wait for it and delay to show simple dataset info.

**Comment by pgunnell** [comment]
Because people complain (with us) that it is not easy and a direct link would help.

**Comment by vkuznet** [comment]
It is not an argument which I should address. There is a way via config query and users should learn. The DAS queries multiple sources and none of them guarantee to be live and if I put everything into single page such page may become irresponsive if some service will go down (which happens a lot) and you'll get MUCH MORE complains.

**Comment by vkuznet** [comment]
My suggestion that you should redirect those who complain to this ticket or ask them to open DAS issue which I can address. So far I see no action needs to be done here, therefore I'm closing the ticket.
