### ISSUE TITLE
Cannot view all files within block

### ISSUE THREAD

**Issue by KatyEllis** [dmwm/das2go#25]
Hi, 

I am using DAS to query the files within block:
/TTToSemiLeptonic_mtop166p5_TuneCP5_13TeV-powheg-pythia8/RunIISummer19UL17RECO-106X_mc2017_realistic_v6-v2/AODSIM#d3ae4ba2-2c38-40dc-8152-421e71ce4a21

I see the block contains 133 files. I can view the first 50 but I cannot find a way to view the next pages. If I click 'next' page, I see this message:

> No results found DAS unable to find any results for your query. Please revisit your query by reviewing DAS query guide or submit a DAS github   issue to resolve your query request.

I also tried changing the number of viewable results from 50 to 150, but this did not work, and I only see 50 results.

**Comment by vkuznet** [comment]
Katy,
I can reproduce the problem and should fix it.

Meanwhile, you can get full list of files use dasgoclient (CLI) interface.
Just login to lxplus and do
voms-proxy-init -voms cms -rfc
dasgoclient -query="file block=/TTToSemiLeptonic_mtop166p5_TuneCP5_13TeV-powheg-pythia8/RunIISummer19UL17RECO-106X_mc2017_realistic_v6-v2/AODSIM#d3ae4ba2-2c38-40dc-8152-421e71ce4a21"

And, you'll get all of your files.

**Comment by KatyEllis** [comment]
Great, thanks in advance for the fix, and also for the command line query.

**Comment by vkuznet** [comment]
The issue is specific to block query where we need to escape '#' in a query. I fixed it in master head in this commit 0462238..d71c5c5, will schedule it to next cmsweb production upgrade.
