### ISSUE TITLE
malformed query information

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/das2go#3]
The old das tool provides more useful information for locating where a typo is in a query. Compare the das and das2go webpages for this query with a space in the middle of the dataset name:

https://cmsweb.cern.ch/das2go/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset+dataset%3D%2Fabcdefghijk%2Flmnopqrstuv%2Fwxy+z%2F

https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset+dataset%3D%2Fabcdefghijk%2Flmnopqrstuv%2Fwxy+z%2F

In the das webpage you can easily find the problem with the -----------------------------------------------^

**Comment by vkuznet** [comment]
Andrew, the code now is ready, but I need time to test it. The unfortunate side is that I don't have time to include it in upcoming June cmsweb upgrade since it is only few days away, but I'll include these changes to next (July) upgrade on cmsweb.

**Comment by vkuznet** [comment]
deployed to production
