### ISSUE TITLE
dasgoclient query does not return value

### ISSUE THREAD

**Issue by katilp** [dmwm/das2go#31]
I'm using the following dasgoclient query to estimate the volume of legacy data and it works as expected  for this MINIAOD query (for example)

```
$ dasgoclient -query "block dataset=/*/Run2017*09Aug2019_UL2017*/MINIAOD | sum(block.size)"
sum(block.size): 2.12740409597139e+14
```

(Curiously, the same query does not work on DAS web UI while it used to work earlier).

However, for another query, this time for NANOAOD, the dasgoclient query returns no result even if the datasets exist:

```
$ dasgoclient -query "block dataset=/*/Run2017*UL2017_MiniAODv1_NanoAODv2*/NANOAOD | sum(block.size)"
$ dasgoclient -query "dataset=/*/Run2017*UL2017_MiniAODv1_NanoAODv2*/NANOAOD"
/BTagCSV/Run2017B-UL2017_MiniAODv1_NanoAODv2-v1/NANOAOD
/BTagCSV/Run2017C-UL2017_MiniAODv1_NanoAODv2-v1/NANOAOD
/BTagCSV/Run2017D-UL2017_MiniAODv1_NanoAODv2-v1/NANOAOD
/BTagCSV/Run2017E-UL2017_MiniAODv1_NanoAODv2-v1/NANOAOD
.....
```

Is there something I should do differently?

**Comment by vkuznet** [comment]
Kati,
you brought a very interesting use-cases. Let's break them down.

- all the blocks for dataset=/*/Run2017*09Aug2019_UL2017*/MINIAOD comes from
Phedex. For example (I'll use only subset to reduce the time)
./dasgoclient -query="block dataset=/ZeroBias9/Run2017*09Aug2019_UL2017*/MINIAOD" -json
returns JSON records and you can see from which services the records comes from.
In this case, it is
"services":["phedex:blockReplicas"]

The dasgoclient still has Phedex as a data-source even though the Phedex is
officially retired. On DAS web we disabled Phedex as a data-source and therefor
you don't see these records (the sum(block.size) is an aggregator which is
applied to found records, so I omit it for simplicity).

You may explicitly use "system=XXX" in your query, e.g.
block dataset=... system=dbs3
should return blocks for a given dataset which comes from DBS,
while
block dataset=... system=phedex
may return blocks which are registered in Phedex, etc.

- For you second query
dataset=/*/Run2017*UL2017_MiniAODv1_NanoAODv2*/NANOAOD
all blocks comes from DBS and they are not in Phedex anymore, therefore
the query
block dataset=/*/Run2017*UL2017_MiniAODv1_NanoAODv2*/NANOAOD
is not resolved in Phedex. Therefore, you don't get the block info.

Instead, what you should do properly is to get list of dataset and for each
dataset get block info, then this query will be resolved in DBS. For instance,
I can do
dasgoclient -query "block dataset=/ZeroBias8/Run2017C-UL2017_MiniAODv1_NanoAODv2-v2/NANOAOD | sum(block.size)"
sum(block.size): 1.0035513104e+10

The difference in underlying APIs, the DBS API requires a full dataset name.
While Phedex APIs were fine with dataset pattern.

Moreover, I hope you understand that pattern queries require more time to
process. Therefore, it is advisable to only use them within single system,
i.e. resolve pattern into list of dataset. And, then loop over dataset to get
detailed info.

My advice, change your queries to do the following:
- get list of datasets first
- loop over list of dataset to get block information from each individual
dataset.

Here is pseudo-code:

datasets=`dasgoclient -query="dataset=/*/Run2017*UL2017_MiniAODv1_NanoAODv2*/NANOAOD"`
totalBlockSize=0
for d in $datasets; do
   blkSize=`dasgoclient -query="block dataset=$d | sum(block.size)"`
   totalBlockSize+=blkSize
done

Best,
Valentin.

**Comment by katilp** [comment]
OK, thanks! That explains. I'll try what you suggest. I need these queries for total data volume estimates, that's why I used pattern queries. But no problem for looping over the list, that's good to know.

**Comment by katilp** [comment]
Hi Valentin,

I have still a question on this. I did the query with a dataset loop, but for MINIAOD (which I can compare) I get different values when first looping and then summing compared to what I get from a direct pattern query with `dasgoclient`. The difference appears for the first part of the 2016 datasets (94 vs 118 TB) and for the 2018 datasets (232 vs 281 TB).

From my query script doing the loop, I get the following values (in TB):

```
$ ./data-query.sh 
MiniAOD (2016 - two first values -, 2017 and 2018):
94.1459
63.3963
211.745
231.69
NanoAOD (2016, 2017, 2018):
5.62214
6.52471
5.65735
```
For MINIAOD, the corresponding values from a direct pattern query are:

- 2016: `dataset dataset=/*/*21Feb2020*UL2016_HIPM-v*/MINIAOD` (129 datasets) and `dataset dataset=/*/*21Feb2020_UL2016-*/MINIAOD` (89 datasets)
  ```
  $ dasgoclient -query "block dataset=/*/*21Feb2020*UL2016_HIPM-v*/MINIAOD | sum(block.size)"
  sum(block.size): 1.18428968336501e+14
  $ dasgoclient -query "block dataset=/*/*21Feb2020_UL2016-*/MINIAOD | sum(block.size)"
  sum(block.size): 6.3336327260316e+13
  ```
- 2017:  `/*/Run2017*09Aug2019_UL2017*/MINIAOD` (198 datasets)
  ```
  $ dasgoclient -query "block dataset=/*/Run2017*09Aug2019_UL2017*/MINIAOD | sum(block.size)"
  sum(block.size): 2.12740409597139e+14
  ```
- 2018: `/*/Run2018*12Nov2019_UL2018*/MINIAOD` (120 datasets)
  ```
  $ dasgoclient -query "block dataset=/*/Run2018*12Nov2019_UL2018*/MINIAOD | sum(block.size)"
  sum(block.size): 2.81469306058378e+14
  ```

My query script `data-query.sh` is:

```
#!/bin/bash

echo "MiniAOD (2016 - two first values -, 2017 and 2018):"
allMiniQueries=("dataset=/*/*21Feb2020*UL2016_HIPM-v*/MINIAOD" "dataset=/*/*21Feb2020_UL2016-*/MINIAOD" "dataset=/*/Run2017*09Aug2019_UL2017*/MINIAOD" "dataset=/*/Run2018*12Nov2019_UL2018*/MINIAOD")
for d in ${allMiniQueries[@]}; do
  ./query-loop.sh $d
done

echo "NanoAOD (2016, 2017, 2018):"
allNanoQueries=("dataset=/*/Run2016*UL2016_MiniAODv1_NanoAODv2*/NANOAOD" "dataset=/*/Run2017*UL2017_MiniAODv1_NanoAODv2*/NANOAOD" "dataset=/*/Run2018*UL2018_MiniAODv1_NanoAODv2*/NANOAOD")
for d in ${allNanoQueries[@]}; do
  ./query-loop.sh $d
done
```

and the loop script `query-loop.sh` is:

```
#!/bin/bash

rm sizes
datasets=`dasgoclient -query="$1"`
for d in $datasets;
do
   queryStr=`dasgoclient -query="block dataset=$d | sum(block.size)"`
   num="${queryStr#*:}"
   echo $num  >> sizes
done
awk '{ sum += $1 } END { print sum/1000000000000 }' sizes
```

I must be doing something wrong here. Is there something else I should take into account for those queries which give different total sizes?

**Comment by vkuznet** [comment]
Kati,
I already explained to you that `block dataset=<pattern>` is resolved via phedex API call. As such I doubt that you can trust the results until you verify that ALL blocks are valid. This information is only available in DBS, and you second approach resolves block info from DBS. Therefore, it may explain the difference between the two. As you may aware some data may be transferred (by Phedex or nowadays by Rucio) but may not be final part of dataset (which is what DBS provides).

I suggest that you take few datasets from 2016, and compare individual results from different DAS outputs, e.g.
```
dasgoclient -query "block dataset=/MET/*21Feb2020_UL2016-*/MINIAOD" -json
```
will give you JSON output (including block.size) from Phedex. Then take an individual dataset and its results from DBS using this query:
```
dasgoclient -query="block dataset=/MET/Run2016H-21Feb2020_UL2016-v2/MINIAOD" -json
```
The block `75514ffd-13f3-4d14-9ea7-d562f9222e68` is present in Phedex output, but does not exists in DBS output. While block `6b0f24f9-53af-43f3-8292-51fb6bfac974` exists in both. In latter case, both have identical size 896700951 bytes. Therefore, from API point of view everything is fine.  This explains the difference you see.

You should be aware of these details when doing queries.

And, for the record, you should never start your query with wildcard pattern, e.g. `dataset=/*/*21Feb2020_UL2016-*/MINIAOD` is really bad query since it creates lots of load on DBS DB since it starts with wildcard pattern. While query `dataset=/MET/*21Feb2020_UL2016-*/MINIAOD` is much better since DB only takes subset of queries with `/MET` string. Please keep this in mind when you do aggregation. That's why the second approach I suggest is much better from stress point of view. First, you can all you dataset names resolved, and then you query info for each individual dataset.

**Comment by katilp** [comment]
Dear Valentin, many thanks for these clarifications. Please understand that I do not do these queries for fun but because I need the results. I understand that a query starting with a wildcard pattern is a bad one, but I have to get the list of files corresponding this pattern from somewhere first. I can store the result for subsequent steps to avoid repeating the wildcard queries.

For the dataset sizes, can you confirm if the dataset size given in DAS web UI query for a single dataset, e.g 56.2 GB in:

![image](https://user-images.githubusercontent.com/5859918/112820906-65a10180-9086-11eb-8667-e5f3f3fd0da2.png)

can be considered to be correct? If yes, is there a way to get that number in a `dasgoclient` query without summing the block sizes?

Many thanks!

**Comment by katilp** [comment]
Just to update, if I sum up the values indicated as "size" I get the value of 94 TB (compared to 118 TB) for the 2016 datasets. As this comes from the values indicated by DAS in normal single dataset queries,  maybe something should be done to correct the displayed values (if they are wrong). Or at least to add a warning.

**Comment by vkuznet** [comment]
Kati, if please don't past screen shot and rather provide real query, such that I can cut and paste it into web or dasgoclient. From screenshot I need to retype every single character and it is easy to make a mistake.

The query you're looking for is  this one:
```
dasgoclient -query "summary dataset=/BTagCSV/Run2016B-21Feb2020_ver1_UL2016_HIPM-v1/MINIAOD" -json
[
{"das":{"expire":1617017914,"instance":"prod/global","primary_key":"summary","record":1,"services":["dbs3:summary4dataset_run"]},"qhash":"a511c4153485dc0a67bd9ddd5ccb1661","summary":[{"file_size":56230698366,"nblocks":10,"nevents":1972666,"nfiles":30,"nlumis":6657,"num_block":10,"num_event":1972666,"num_file":30,"num_lumi":6657}]}
]
```

The summary provides full summary of the dataset. And, yes the file size reports full size of all VALID files in a dataset. This is correct value as it is calculated by DBS at DB level.

**Comment by katilp** [comment]
OK, thanks, now I've understood. So I can assume the size values from the individual dataset queries to be correct, and it is the block sum query that overestimates the size because it may take some non-valid blocks in the sum. Many thanks for your help!
