### ISSUE TITLE
buggy links in cmsweb.cern.ch/das

### ISSUE THREAD

**Issue by michael-pitt** [dmwm/das2go#36]
I'm using the [web interface](https://cmsweb.cern.ch/das/), and I tackle the following error:
I'm searching for children of a given file:
```
child file=/store/mc/RunIISummer20UL18RECO/GGToEE_Pt-35_Elastic_13TeV-lpair/AODSIM/106X_upgrade2018_realistic_v11_L1v1-v2/100000/027C3A23-DAA8-1449-9047-A418996EEC2E.root
```
The output is [two files](https://cmsweb.cern.ch/das/request?instance=prod/global&input=child+file%3D%2Fstore%2Fmc%2FRunIISummer20UL18RECO%2FGGToEE_Pt-35_Elastic_13TeV-lpair%2FAODSIM%2F106X_upgrade2018_realistic_v11_L1v1-v2%2F100000%2F027C3A23-DAA8-1449-9047-A418996EEC2E.root), but when I click on one of the files to view its related info, web interface forwards me to the following search line:
```
dataset=/store/mc/RunIISummer20UL18MiniAOD/GGToEE_Pt-35_Elastic_13TeV-lpair/MINIAODSIM/106X_upgrade2018_realistic_v11_L1v1-v2/100000/80B92674-24B6-9642-87C4-3C41A752F15E.root
```
with `DBS unable to unmarshal the data into DAS record...` error.
It should be `file` instead of `dataset` in the search command. 
This error might lead a user to conclude that the file is missing, so it is important to make this fix.

Thanks!

**Comment by vkuznet** [comment]
done and deployed to cmsweb, closing the ticket
