### ISSUE TITLE
Dataset query with run/date option in DAS

### ISSUE THREAD

**Issue by sarakm0704** [dmwm/das2go#45]
Dear experts,

I wanted to know if there is any EGamma dataset containing run 355872 released, trying `dataset=/EGamma/*/* run=355872` or something like `dataset=/EGamma/*/* run between(or in) [355815, 355915]`, but it did not show anything.

And I tried with `dataset=/EGamma/*/* date between [20220718, 20220726]`, it shows only RAW dataset..

Then I looked up `dataset run=355872` itself and could find EGamma Run2022C datasets. 
For example `dataset=/EGamma/Run2022C-PromptReco-v1/MINIAOD` has run 355872, created 2022-07-20.

Is this expected? If this is not the recommended way to use run/date option, what supposes to be the best option to find a specific dataset with a given run / date?

Best regards,
Jieun

**Comment by vkuznet** [comment]
Jieun, you are combing pattern query (`dataset=/EGamma/*/*`) with precise queries which is not meant to be. Instead, you should do this as a sequence of steps:
- first identify list of dataset for your goal, e.g. get list of dataset which match your pattern, e.g.
```
# get EGamma datasets with RAW data tier
dataset=/EGamma/*/*RAW

# or get EGamme datasets with MINIAOD tier
dataset=/EGamma/*/MINIAOD
```

- Now, you have a list of dataset, and for each dataset you may list corresponding file,run,lumi attributes, e.g.
```
# find file,run info of a given dataset
file,run dataset=/AlCaP0/Run2022C-v1/RAW

# or you can find all runs within given dataset
run dataset=/AlCaP0/Run2022C-v1/RAW
```
and here you can grep for a specific run.

Or, as you already shown you can use `dataset run=355872` to get list of datasets which contains this run. When I run this query with `dasgoclient` I see that it yields 365 datasets. Then you can walk thought this list to get list of file,run if you want to.

The `date` has different meaning in different queries. This is a parameter in database which is associated with specific attribute, i.e. date in dataset table correspond to dataset date creation. Therefore, when you use it with dataset condition it applies to dataset itself and not date of the taken run. Therefore, I don't understand why you apply this condition and what you mean by using the date parameter.

Let me know if you need more information or would like to clarify it further.

**Comment by sarakm0704** [comment]
Thanks a lot for the clarification. Indeed I thought using pattern + precise query would work together.

I used the `date` query as an alternative option to `run` because the dataset will be created after the date of the run taken. And now I see `dataset=/EGamma/*/* date in [20220718, 20220726]` shows list of EGamma datasets...
