### ISSUE TITLE
Can't find storage site of a existed file

### ISSUE THREAD

**Issue by PKUfudawei** [dmwm/das2go#48]
I couldn't find any site for file `/store/mc/RunIISummer20UL18NanoAODv9/ZJetsToQQ_HT-200to400_TuneCP5_13TeV-madgraphMLM-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v2/2550000/B369327F-C0CD-564B-9B16-8CCD9BD9DEF4.root`. You can refer to this [link](https://cmsweb.cern.ch/das/request?instance=prod/global&input=site+file%3D%2Fstore%2Fmc%2FRunIISummer20UL18NanoAODv9%2FZJetsToQQ_HT-200to400_TuneCP5_13TeV-madgraphMLM-pythia8%2FNANOAODSIM%2F106X_upgrade2018_realistic_v16_L1v1-v2%2F2550000%2FB369327F-C0CD-564B-9B16-8CCD9BD9DEF4.root)

**Comment by PKUfudawei** [comment]
Actually, it exists on [file-query](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=file%3D%2Fstore%2Fmc%2FRunIISummer20UL18NanoAODv9%2FZJetsToQQ_HT-200to400_TuneCP5_13TeV-madgraphMLM-pythia8%2FNANOAODSIM%2F106X_upgrade2018_realistic_v16_L1v1-v2%2F2550000%2FB369327F-C0CD-564B-9B16-8CCD9BD9DEF4.root) page but no site info within it, I can't  `xrdcp` it. I'm unsure if there is something wrong with the storage on remote servers.

**Comment by PKUfudawei** [comment]
Updates:  
I found it's weird that although no site info with this file, I can still download it with `xrdcp` by chance!  
<img width="961" alt="Try downloading file twice" src="https://user-images.githubusercontent.com/87391608/196603781-e9f0d691-5948-4181-b482-07e547385cb5.png">. 
So what's the underlying mechanism for that? Sometimes unaccessible but sometimes accessible

**Comment by vkuznet** [comment]
@PKUfudawei , this is not appropriate channel to discuss these issue. The DAS only fetches information from upstream CMS services. For site related questions I suggest you use CMS Mattermost channels, like Computing operations or Rucio.

**Comment by PKUfudawei** [comment]
> @PKUfudawei , this is not appropriate channel to discuss these issue. The DAS only fetches information from upstream CMS services. For site related questions I suggest you use CMS Mattermost channels, like Computing operations or Rucio.

Thanks @vkuznet , sry for discussing here cuz I followed the issue link on DAS :( . So could u kindly invite me or link me to the channels you mentioned above? I couldn't find them by myself. My username is `dfu` on mattermost. I'll close this issue when I moved to mattermost channels

**Comment by vkuznet** [comment]
Here is direct link: https://mattermost.web.cern.ch/cms-o-and-c/channels/computing-operations
