### ISSUE TITLE
DAS dataset showing 0 size/files/events when files exist

### ISSUE THREAD

**Issue by borzari** [dmwm/das2go#60]
I am not sure if I should ask this here or in some ticket or cms-talk. Please, tell me otherwise.

I have some datasets registered on DAS that show 0 files, size or events, even though the files exist somewhere. As an example, dataset [/DYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8/borzari-Run3Summer22EEDRPremix-124X_mcRun3_2022_realistic_postEE_v1-v3_EXODisappTrkPAT-9d47b08148d63ab5a7c705d3cebd063d/USER](https://cmsweb.cern.ch/das/request?input=dataset%3D%2FDYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8%2Fborzari-Run3Summer22EEDRPremix-124X_mcRun3_2022_realistic_postEE_v1-v3_EXODisappTrkPAT-9d47b08148d63ab5a7c705d3cebd063d%2FUSER&instance=prod/phys03) has files in `/store/user/borzari/DYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8/Run3Summer22EEDRPremix-124X_mcRun3_2022_realistic_postEE_v1-v3_EXODisappTrkPAT/230827_180418/0000/`, but the DAS information shows 0 files.

I also have the same information if I use `dasgoclient -query 'dataset dataset=/DYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8/borzari-Run3Summer22EEDRPremix-124X_mcRun3_2022_realistic_postEE_v1-v3_EXODisappTrkPAT-9d47b08148d63ab5a7c705d3cebd063d/USER' -json`.

I noticed that this usually happens for older datasets, because when this dataset was created, DAS showed the correct information associated with it.

Is this behavior of changing the registered information to 0 an expected feature? Is there a way to revert this and put the initial information back in DAS?

**Comment by belforte** [comment]
@borzari please see https://cms-talk.web.cern.ch/t/dbs-phys03-files-wrongly-invalidated/31152/2

**Comment by borzari** [comment]
Thank you @vkuznet for the answer and suggestion!

And thank you @belforte as well for the solution! The command seems to have worked.

Just a quick question: will the correct size/files/events information be displayed when searching for the dataset at some point? This isn't that important, but would be good to have the information available again for the datasets that have the files validity modified (asking because the dataset information is still 0, but the files query worked fine).

**Comment by vkuznet** [comment]
May be I was not clear, with `status=*` flag DAS shows both valid and invalid files, in your case all files are invalid. Therefore, without this flags DAS will still show 0 files unless someone in operations will change these files back to valid status. When and if it will be done the DAS will show again valid files.
