### ISSUE TITLE
Data Set file opening issue

### ISSUE THREAD

**Issue by Bharat0014** [dmwm/das2go#63]
i am searching dataset (dataset=/LQToCMu_M-950_BetaOne_TuneCUETP8M1_13TeV-pythia8/RunIISummer16NanoAODv7-PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8-v1/NANOAODSIM) this is showing some result. But when i click on the Files, it's keep on running not showing the root file 
![Screenshot from 2024-05-10 14-40-03](https://github.com/dmwm/das2go/assets/101450721/88c93f76-a24e-44b3-af88-d49958531584)
so i am not able to see root file for any data set.

**Comment by vkuznet** [comment]
thanks for reporting, it is fixed now. Das server had some issues and I restarted it few hours ago. I checked your query now it and it works for me now.
