### ISSUE TITLE
problem access on file in a dataset

### ISSUE THREAD

**Issue by welmeten** [dmwm/das2go#69]
I'm running crab task on the dataset "/DoubleEG/Run2017F-UL2017_MiniAODv2-v2/MINIAOD" 
but few carb jobs failed as it isn't able to open one file in the dataset,
'/store/data/Run2017F/DoubleEG/MINIAOD/UL2017_MiniAODv2-v2/280000/8F330912-1587-A246-8EA0-05FA9AB65F1B.root'
 I check the file with "checkfile"
it gives (*) then with --checksum it gives(**). which IMHO means that the FNAL disk storage has this file name in its namespace, but does not really have the file content on disk. Maybe a disk pool is temporarily offline. Or maybe the file was lost.

What is the solution for that?

(*)
Rucio client intialized for account welmeten
looking up LFN in DBS prod/global
file status in DBS is VALID
file belongs to:
dataset: /DoubleEG/Run2017F-UL2017_MiniAODv2-v2/MINIAOD
block: /DoubleEG/Run2017F-UL2017_MiniAODv2-v2/MINIAOD#41893321-4959-4558-a6bc-3ecece57ee9d
dataset is : VALID
Check information in Rucio
LFN found in Rucio with matching block/dataset parentage
LFN has a tape replica at T0_CH_CERN_Tape
LFN has 1 disk replicas
List of disk replicas. Check that file exists and has correct size (3529064377 bytes):
RSE status
T1_US_FNAL_Disk OK
Disk replicas files may still be corrupted
run again with --checksum for a thorough check. Beware: SLOW and needs GB’s of disk

(**)
Copying 3529064377 bytes davs://cmsdcadisk.fnal.gov:2880/dcache/uscmsdisk/store/data/Run2017F/DoubleEG/MINIAOD/UL2017_MiniAODv2-v2/280000/8F330912-1587-A246-8EA0-05FA9AB65F1B.root => file:///tmp/belforte/testFile_m5wpoirm

gfal-copy error: 5 (Input/output error) - Result HTTP 500 : Unexpected server error: 500 , while readding after 1 attempts

**Comment by vkuznet** [comment]
Please ask in CMSTalk, the das2go has nothing to do with physical files availability. Closing because it is not issue with das2go.

**Comment by todor-ivanov** [comment]
thanks @vkuznet, I was searching for the words to express the same.
